apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1 # Reduce replicas for the dev environment
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:latest # Using nginx as the image in dev
