apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:latest # Default image for base
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
